### PR TITLE
Add Pagination support

### LINKED ISSUE #16: Missing support for pagination
There is a while that we tried for the first time to use this package, but for some reason we opted out of it.

Now I think that I remember the main reason that we created the whole code for the responses extracts: the lack of pagination.

I haven't found a way to set the **resultsperpage** and **page** params :disappointed:

### PR DESCRIPTION
**Pull request by WesleyBatista**
Closes #16

### CODE REVIEW

**Comment by rpkilby** [comment]
Hi @WesleyBatista - this looks great. If you could add a couple of sanity tests to [`FilteringTests`](https://github.com/ITNG/SurveyGizmo/blob/master/tests/test_resource.py#L35-L83), I'd merge this.

**Comment by WesleyBatista** [comment]
Cool! I will do it :)

**Comment by WesleyBatista** [comment]
Done! Needs something else?

**Comment by rpkilby** [comment]
Looks good to me - thanks for contributing. I'll try to make a release some time this weekend.

**Comment by rpkilby** [comment]
This should be available now on pypi as version 1.2.2

**Pull request merged**
